In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv("C:/Users/Sanjana/Downloads/bank.csv")

In [3]:
dataset.shape

(11162, 17)

In [4]:
dataset.tail()

age          job  marital  education default  balance housing loan  \
11157   33  blue-collar   single    primary      no        1     yes   no   
11158   39     services  married  secondary      no      733      no   no   
11159   32   technician   single  secondary      no       29      no   no   
11160   43   technician  married  secondary      no        0      no  yes   
11161   34   technician  married  secondary      no        0      no   no   

        contact  day month  duration  campaign  pdays  previous poutcome  \
11157  cellular   20   apr       257         1     -1         0  unknown   
11158   unknown   16   jun        83         4     -1         0  unknown   
11159  cellular   19   aug       156         2     -1         0  unknown   
11160  cellular    8   may         9         2    172         5  failure   
11161  cellular    9   jul       628         1     -1         0  unknown   

      deposit  
11157      no  
11158      no  
11159      no  
11160      no  
11161      no

In [5]:
dataset.isnull().any()

age          False
job          False
marital      False
education    False
default      False
balance      False
housing      False
loan         False
contact      False
day          False
month        False
duration     False
campaign     False
pdays        False
previous     False
poutcome     False
deposit      False
dtype: bool

In [6]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
dataset["loan"]=le.fit_transform(dataset["loan"])
dataset["housing"]=le.fit_transform(dataset["housing"])
dataset["job"] = le.fit_transform(dataset["job"])
dataset["marital"] = le.fit_transform(dataset["marital"])
dataset["education"] = le.fit_transform(dataset["education"])
dataset["default"] = le.fit_transform(dataset["default"])
dataset["contact"] = le.fit_transform(dataset["contact"])
dataset["month"] = le.fit_transform(dataset["month"])
dataset["poutcome"] = le.fit_transform(dataset["poutcome"])
dataset["deposit"] = le.fit_transform(dataset["deposit"])

In [7]:
dataset.head()

age  job  marital  education  default  balance  housing  loan  contact  \
0   59    0        1          1        0     2343        1     0        2   
1   56    0        1          1        0       45        0     0        2   
2   41    9        1          1        0     1270        1     0        2   
3   55    7        1          1        0     2476        1     0        2   
4   54    0        1          2        0      184        0     0        2   

   day  month  duration  campaign  pdays  previous  poutcome  deposit  
0    5      8      1042         1     -1         0         3        1  
1    5      8      1467         1     -1         0         3        1  
2    5      8      1389         1     -1         0         3        1  
3    5      8       579         1     -1         0         3        1  
4    5      8       673         2     -1         0         3        1

In [8]:
dataset.shape

(11162, 17)

In [9]:
x=dataset.iloc[:,0:16].values
y=dataset.iloc[:,16].values

In [10]:
x

array([[ 59,   0,   1, ...,  -1,   0,   3],
       [ 56,   0,   1, ...,  -1,   0,   3],
       [ 41,   9,   1, ...,  -1,   0,   3],
       ...,
       [ 32,   9,   2, ...,  -1,   0,   3],
       [ 43,   9,   1, ..., 172,   5,   0],
       [ 34,   9,   1, ...,  -1,   0,   3]], dtype=int64)

In [11]:
y

array([1, 1, 1, ..., 0, 0, 0])

In [30]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 1000)

In [31]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [32]:
x_test

array([[-0.86361104, -0.1477359 , -0.30854901, ..., -0.48069866,
        -0.368907  ,  0.5205717 ],
       [ 0.88023396, -1.3937954 ,  1.29003552, ...,  2.87293007,
         3.80325053, -2.48055552],
       [-0.19928913, -1.08228053, -0.30854901, ..., -0.48069866,
        -0.368907  ,  0.5205717 ],
       ...,
       [-0.19928913,  1.40983849, -0.30854901, ..., -0.48069866,
        -0.368907  ,  0.5205717 ],
       [-0.36536961, -1.08228053, -0.30854901, ..., -0.48069866,
        -0.368907  ,  0.5205717 ],
       [-1.11273175, -0.1477359 ,  1.29003552, ...,  1.58103088,
         1.48538524, -0.47980404]])

In [33]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()
logreg.fit(x_train,y_train)

C:\Users\Sanjana\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [34]:
ypred = logreg.predict(x_test)

In [35]:
ypred

array([1, 1, 0, ..., 0, 0, 1])

In [36]:
y_test

array([1, 1, 0, ..., 0, 0, 1])

In [37]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(ypred,y_test)
accuracy

0.8056426332288401

In [38]:
dataset.head()

age  job  marital  education  default  balance  housing  loan  contact  \
0   59    0        1          1        0     2343        1     0        2   
1   56    0        1          1        0       45        0     0        2   
2   41    9        1          1        0     1270        1     0        2   
3   55    7        1          1        0     2476        1     0        2   
4   54    0        1          2        0      184        0     0        2   

   day  month  duration  campaign  pdays  previous  poutcome  deposit  
0    5      8      1042         1     -1         0         3        1  
1    5      8      1467         1     -1         0         3        1  
2    5      8      1389         1     -1         0         3        1  
3    5      8       579         1     -1         0         3        1  
4    5      8       673         2     -1         0         3        1

In [39]:
logreg.predict([[41,0,1,1,0,2343,1,0,2,5,8,1467,1,-1,0,3]])

array([1])